import type { Metadata } from 'next';
import Navigation from '@/components/navigation';
import Footer from '@/components/footer';

export const metadata: Metadata = {
	title: 'Invoice Generator',
	description: 'Generated by create next app',
};

export default function IndexLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<>
			<Navigation />
			{children}
			<Footer />
		</>
	);
}
