import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from '@/components/ui/toaster';
import './globals.css';
import Splash from '@/components/splash';
import CookieConsent from '@/components/cookie-consent';
import Script from 'next/script';

const sans = Inter({
	variable: '--font-sans',
	subsets: ['latin'],
	preload: true,
});

export const metadata: Metadata = {
	title: 'Invoice Generator',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang='en'>
			<body className={`${sans.className} antialiased`}>
				<ThemeProvider attribute='class' defaultTheme='dark'>
					<Splash />
					{children}
					<CookieConsent />
					<Toaster />
				</ThemeProvider>
			</body>
			<Script src='https://challenges.cloudflare.com/turnstile/v0/api.js' strategy='lazyOnload' />
		</html>
	);
}
