import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';
import './globals.css';
import Navigation from '@/components/navigation';

const sans = Inter({
	variable: '--font-sans',
	subsets: ['latin'],
	preload: true,
});

export const metadata: Metadata = {
	title: 'Invoice Generator',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang='en'>
			<body className={`${sans.className} antialiased`}>
				<ThemeProvider attribute='class' enableSystem defaultTheme='system'>
					<Navigation />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
